### ISSUE TITLE
Oppdatering av ingresser til fpabakus

### ISSUE THREAD

**Issue by mrsladek** [navikt/helse-sparkelapper#15]
Hei, 

Vi har tenkt å sanere en del gamle ingresser - dette innebærer at dere oppdaterer lenkene til fpabakus til:

https://fpabakus.dev.intern.nav.no i dev
https://fpabakus.intern.nav.no i prod

Takk på forhånd.

**Comment by fraadsbrandth** [comment]
Er i ferd med å flytte de to appene som går mot abakus til GCP, så de er på veg over til å bruke https://fpabakus.dev-fss-pub.nais.io/ & https://fpabakus.prod-fss-pub.nais.io @mrsladek 👍
